'use client'

import { useState } from 'react'
import Image from 'next/image'

interface SafeImageProps {
  src: string
  alt: string
  className?: string
  fallbackSrc?: string
  loading?: 'lazy' | 'eager'
  width?: number
  height?: number
  // When provided, mobile devices (<=768px) will use a Google Places photo generated by the server
  // without exposing API keys client-side.
  mobileQuery?: string
  mobileMaxWidth?: number
  // If true, mobileQuery photo will override the src on mobile. Default false to keep images consistent across devices.
  mobileOverride?: boolean
}

export default function SafeImage({
  src,
  alt,
  className = '',
  fallbackSrc = 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop&auto=format&q=80',
  loading = 'lazy',
  width = 800,
  height = 600,
  mobileQuery,
  mobileMaxWidth = 600,
  mobileOverride = false
}: SafeImageProps) {
  const [imgSrc, setImgSrc] = useState(src)
  const [hasError, setHasError] = useState(false)
  // Default to not loading so SSR renders an <img> even if hydration is blocked
  const [isLoading, setIsLoading] = useState(false)

  const handleError = () => {
    // First try mobile Places photo if provided and not already attempted
    const mobileSrc = mobileQuery ? `/api/places/photo?q=${encodeURIComponent(mobileQuery)}&maxwidth=${mobileMaxWidth}` : ''
    if (mobileSrc && imgSrc !== mobileSrc) {
      setImgSrc(mobileSrc)
      setIsLoading(true)
      return
    }
    if (!hasError && imgSrc !== fallbackSrc) {
      setHasError(true)
      setImgSrc(fallbackSrc)
      setIsLoading(true) // Reset loading for fallback image
    } else if (hasError && imgSrc === fallbackSrc) {
      // If even primary fallback fails, try a different reliable fallback
      const secondaryFallback = 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&h=600&fit=crop&auto=format&q=80'
      setImgSrc(secondaryFallback)
      setIsLoading(true)
    } else {
      // If all fallbacks fail, keep loading state false to show placeholder
      setIsLoading(false)
    }
  }

  const handleLoad = () => {
    setIsLoading(false)
  }

  // Construct a server-side generated mobile photo URL if requested
  const mobileSrc = mobileQuery ? `/api/places/photo?q=${encodeURIComponent(mobileQuery)}&maxwidth=${mobileMaxWidth}` : undefined

  return (
    <div className={`relative overflow-hidden ${className}`}>
      {/* Only override the source on mobile if explicitly requested. Default keeps the same image across devices. */}
      {mobileOverride && mobileSrc ? (
        <picture>
          <source media="(max-width: 768px)" srcSet={mobileSrc} />
          <img
            src={imgSrc}
            alt={alt}
            className="w-full h-full object-cover"
            onError={handleError}
            onLoad={handleLoad}
            loading={loading}
            width={width}
            height={height}
          />
        </picture>
      ) : (
        <img
          src={imgSrc}
          alt={alt}
          className="w-full h-full object-cover"
          onError={handleError}
          onLoad={handleLoad}
          loading={loading}
          width={width}
          height={height}
        />
      )}
      {/* Optional lightweight skeleton overlay while loading (won't block SSR image) */}
      {isLoading && (
        <div className="absolute inset-0 bg-gradient-to-br from-gray-100 to-gray-200 animate-pulse" aria-hidden="true" />
      )}
      {/* Error placeholder if both images fail */}
      {hasError && imgSrc === fallbackSrc && !isLoading && (
        <div className="absolute inset-0 bg-gradient-to-br from-red-50 to-red-100 flex items-center justify-center">
          <div className="text-red-400 text-center">
            <svg className="w-10 h-10 mx-auto mb-2" fill="currentColor" viewBox="0 0 24 24">
              <path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"/>
            </svg>
            <p className="text-xs font-medium">Image unavailable</p>
          </div>
        </div>
      )}
    </div>
  )
}